### ISSUE TITLE
Query Summary KeyError

### ISSUE THREAD

**Issue by alfredtangsw** [woctezuma/download-steam-reviews#10]
Hello @woctezuma ! Thanks for your help so far. I encountered a possible issue while querying a batch of Steam appids.

![image](https://user-images.githubusercontent.com/48082063/60062283-27491680-972b-11e9-84d2-7f68c56fbe2b.png)

I decided to extract a large number of reviews (2 years' worth) and it seems to throw an error for review_dict['query_summary ']. I'm not sure why, but it's not consistent either. If I start the querying again after removing the ID from the list of processed IDs, the one that was affected works ok, but then it throws an error for others further down the line.

Could you advise me, please? Thanks!

Code is below
------------
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-25-2fbf1de451ae> in <module>
     10 request_params['day_range'] = (str(search_years*365))  # focus on reviews which were published during the past four weeks
     11 
---> 12 steamreviews.download_reviews_for_app_id_batch(appid_batch1,chosen_request_params=request_params)

~\Anaconda3\lib\site-packages\steamreviews\download_reviews.py in download_reviews_for_app_id_batch(input_app_ids, previously_processed_app_ids, chosen_request_params)
    287 
    288         print('[appID = {}] num_reviews = {} (expected: {})'.format(app_id, len(review_dict['reviews']),
--> 289                                                                     review_dict['query_summary']['total_reviews']))
    290 
    291     print('Game records written: {}'.format(game_count))

KeyError: 'query_summary'

**Comment by alfredtangsw** [comment]
I'm running a smaller batch of queries again, just to check if it was a problem on my end. Maybe I didn't delete some files I should've, because the 2nd time I ran the query last night, it had just passed midnght.

**Comment by alfredtangsw** [comment]
Okay, the smaller batch worked just fine. I'm not so sure where the problem is...

**Comment by alfredtangsw** [comment]
The issue didn't come up again, so closing this for now. Thanks for your time

**Comment by woctezuma** [comment]
The `query_summary` key is set at the first iteration of the loop [at this line](https://github.com/woctezuma/download-steam-reviews/blob/e3c8c18dfd24d3e66589aeb27811cb29d9331fa8/steamreviews/download_reviews.py#L236). If this does not happen, then the first iteration must have failed [at this line](https://github.com/woctezuma/download-steam-reviews/blob/e3c8c18dfd24d3e66589aeb27811cb29d9331fa8/steamreviews/download_reviews.py#L203), which means either the request to Steam API failed or the response was empty (no review). One way to avoid throwing an error is to initialize the `query_summary` key [at this line](https://github.com/woctezuma/download-steam-reviews/blob/e3c8c18dfd24d3e66589aeb27811cb29d9331fa8/steamreviews/download_reviews.py#L184), the program won't crash but this won't fix the failed request or empty response (most likely due to rate limits).

**Comment by woctezuma** [comment]
This should be solved with version 0.8.1.

**Comment by alfredtangsw** [comment]
Understood, and thanks. I'd also like to give some feedback:

![image](https://user-images.githubusercontent.com/48082063/60155350-74f17c00-981c-11e9-85ef-fff5ca124b36.png)

There are times when, such as today, Steam is overloaded with access requests due to sales and we get 502 errors. In this case, I have to delete the IDs from the processed ID txt file and also remove the JSON file, I think? At least, that's what I have been doing.

Would be cool if this process could be automated!

Aside from that, everything is working beautifully. Thanks for putting in the hard work to make it easy for us data scientists to download the data we need :)

**Comment by woctezuma** [comment]
I would not risk automating the deletion of the JSON file on the drive of someone else. I think it is better to leave this task to the user. Indeed, you might want to delete the files and start from scratch, but it might not be the case for every user. 

For instance, in the image attached to your post, I see that the faulty response arose at `offset=4900` for a game with 6862 reviews, and at `offset=13000` for a game with 13572 reviews. Depending on your task, you might want to keep the downloaded reviews and do something with them. Maybe you don't need to have all the reviews and you are happy with 70% of the reviews, or maybe you don't have the time to start the downloading process from scratch. 

Moreover, it would be possible to download the missing reviews and aggregate them to the JSON file. I did not provide the mean to do so, but it is not too complex. What was downloaded is not necessarily useless, it just requires a little additional work from the user to start the download with the right offset, and then aggregate the review data.

Finally, this faulty response ("502 Bad Gateway") should only happen when Steam servers are saturated: as you pointed out, in this case, the reason is that the Steam summer sale, which is the second biggest Steam event (after the Steam winter sale), started yesterday.

**Comment by alfredtangsw** [comment]
Hey @woctezuma, thanks for getting back to me. I understand it may not be the best practise for all users to automate deletion, so I'll just deal with that myself.
