### ISSUE TITLE
[Data missing]id = 730

### ISSUE THREAD

**Issue by NancySnow** [woctezuma/download-steam-reviews#18]
I use 'download_reviews_for_app_id_batch([730])' to download reviews for game which id is '730'.

There should be 6042321 reviews.

But I only get 26499 reviews.

PS:
I tried to check the wrong response status, their cursors are ended with '=' or include'+'.
Your solution is skipping these responses and then requesting another time.
BUT we still miss data. I want to invite you to check the problem together. 
And I will still try to debug, I will send you the solution if I solve the problem. However, I believe you will solute it before me.

Attached is:
```
ownloading reviews for appID = 730
[appID = 730] expected #reviews = 6037843
502 Bad Gateway for appID = 730 and cursor = AoJw2qv1rv0CfdWwjQM=. Cooldown: 10 seconds
502 Bad Gateway for appID = 730 and cursor = AoJwypuNrv0CeI2CjQM=. Cooldown: 10 seconds
502 Bad Gateway for appID = 730 and cursor = AoJw363kqv0Ce+W7iwM=. Cooldown: 10 seconds
Number of queries 150 reached. Cooldown: 310 seconds
502 Bad Gateway for appID = 730 and cursor = AoJ4z+zSnv0CcdW0iQM=. Cooldown: 10 seconds
Faulty response status code = 500 for appID = 730 and cursor = AoJw8JujnP0Cea+QiQM=
[appID = 730] num_reviews = 26499 (expected: 6037843)
```

**Comment by woctezuma** [comment]
For info, if you are only interested in one appID, then you could directly call:

https://github.com/woctezuma/download-steam-reviews/blob/bbff6bb44b94d720ba540c155c249e2273632b66/steamreviews/download_reviews.py#L262-L268

Now, regarding the issue, it seems to arise because of the responses are faulty:
- `502 Bad Gateway` -> https://developer.mozilla.org/fr/docs/Web/HTTP/Status/502
- `500 Internal Server Error` -> https://developer.mozilla.org/docs/Web/HTTP/Status/500

**Comment by woctezuma** [comment]
I am currently running the code on [Google Colab](https://colab.research.google.com/).

![In-progress](https://i.ibb.co/q12j8yc/2021-12-01-12-30-21.png)

There have been 150*5 = 750 queries so far, without any error message. Since each query returns 100 reviews, this amounts to 75 thousand reviews, which is more than what you had when the error arose for you (you mentioned 27 thousand).

https://github.com/woctezuma/download-steam-reviews/blob/bbff6bb44b94d720ba540c155c249e2273632b66/steamreviews/download_reviews.py#L93

I believe you were unlucky and encountered the error during Steam maintenance, which usually happens every Tuesday.

**Comment by woctezuma** [comment]
**Caveat**: if you are interested in games with many reviews (6 million reviews for CS:GO), and if you encounter server errors again, then try to run the code which is inside `download_reviews_for_app_id()` and make sure to have variables accessible in your debugger, or to save them to the disk quite often.

Indeed, it seems I only save reviews to disk at the end of the code of `download_reviews_for_app_id()`, so you would be losing data and wasting time if you notice that the errors happen a lot. It is fine for small games with few reviews, but for big games like CS:GO, it would be painful.

https://github.com/woctezuma/download-steam-reviews/blob/bbff6bb44b94d720ba540c155c249e2273632b66/steamreviews/download_reviews.py#L412-L413
